options { 
	STATIC = false;
	MULTI = true;
	VISITOR = true;
}


PARSER_BEGIN(Parser)

package lang.parser;
public class Parser {
}

PARSER_END(Parser)


SKIP:
{
	" " | "\r" | "\t" | "n"
}


TOKEN:
{
		<HELLO: "hello">
	|	<JAVACC: "javacc">
	|	<JJTREE: "jjtree">
}

ASTHello Hello():
{}
{
	<HELLO> Command() { return jjtThis;}
}

void Command() #void :
{}
{
		JavaCC()
	|	JJTree()
}

void JavaCC():
{}
{
	<JAVACC>
}

void JJTree():
{}
{
	<JJTREE>
}